import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from "react-router";
import { ArrowLeft, Heart, Calendar, CheckCircle } from "lucide-react";
import { novenasData } from "../data/novenas";
import { useNovenaProgress } from "../hooks/useNovenaProgress";
function NovenaCard({ novena }) {
    const navigate = useNavigate();
    const { completedDays, progressPercentage } = useNovenaProgress(novena.id);
    const percentage = progressPercentage(novena.duracao);
    return (_jsxs("div", { onClick: () => navigate(`/novenas/${novena.id}`), className: "bg-church-bg-secondary rounded-xl p-6 border border-church-border-hover \n        hover:border-[#C89B3C]/50 transition-all cursor-pointer \n        hover:-translate-y-1 group shadow-none", children: [_jsxs("div", { className: "flex items-start gap-4 mb-4", children: [_jsx("div", { className: "w-12 h-12 bg-church-bg border border-church-border-hover rounded-full flex items-center justify-center flex-shrink-0 group-hover:scale-110 transition-transform", children: _jsx(Heart, { className: "w-6 h-6 text-church-accent-hover" }) }), _jsxs("div", { className: "flex-1", children: [_jsx("h3", { className: "text-xl font-serif text-church-accent mb-2 group-hover:text-church-accent-hover transition-colors", children: novena.titulo }), _jsx("p", { className: "text-church-text/60 text-sm mb-3 line-clamp-2", children: novena.descricao }), _jsxs("div", { className: "flex items-center gap-4 text-sm text-church-text/40", children: [_jsxs("div", { className: "flex items-center gap-1", children: [_jsx(Calendar, { className: "w-4 h-4" }), _jsxs("span", { children: [novena.duracao, " dias"] })] }), completedDays.length > 0 && (_jsxs("div", { className: "flex items-center gap-1 text-church-accent font-medium", children: [_jsx(CheckCircle, { className: "w-4 h-4" }), _jsxs("span", { children: [completedDays.length, "/", novena.duracao, " conclu\u00EDdos"] })] }))] })] })] }), _jsx("div", { className: "w-full bg-church-bg h-1.5 rounded-full mt-4 overflow-hidden border border-church-border-hover", children: _jsx("div", { className: "bg-[#C89B3C] h-full transition-all duration-500 opacity-80", style: { width: `${percentage}%` } }) })] }));
}
export function NovenasPage() {
    const navigate = useNavigate();
    return (_jsxs("div", { className: "min-h-screen bg-church-bg text-church-text font-sans", children: [_jsx("header", { className: "bg-church-bg/95 border-b border-church-border backdrop-blur-md sticky top-0 z-50 py-6 transition-all", children: _jsxs("div", { className: "max-w-7xl mx-auto px-4", children: [_jsxs("button", { onClick: () => navigate("/igreja"), className: "flex items-center gap-2 text-church-accent hover:text-church-accent-hover mb-4 transition-colors", children: [_jsx(ArrowLeft, { className: "w-5 h-5" }), "Voltar"] }), _jsxs("div", { className: "flex items-center justify-center gap-3", children: [_jsx(Heart, { className: "w-8 h-8 text-church-accent-hover" }), _jsx("h1", { className: "text-4xl text-center font-serif text-church-accent", children: "Novenas" })] })] }) }), _jsxs("div", { className: "max-w-5xl mx-auto px-4 py-12", children: [_jsxs("div", { className: "bg-church-bg-secondary rounded-2xl p-8 mb-12 border border-church-border-hover shadow-none", children: [_jsx("div", { className: "overflow-hidden h-64 mb-8 rounded-xl", children: _jsx("img", { src: "https://images.unsplash.com/photo-1559536454-5a69386e8075?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaHVyY2glMjBpbnRlcmlvciUyMGNhbmRsZXN8ZW58MXx8fHwxNzczNDA5ODYyfDA&ixlib=rb-4.1.0&q=80&w=1080", alt: "Velas na Igreja", className: "w-full h-full object-cover" }) }), _jsx("p", { className: "text-church-text/80 text-lg leading-relaxed text-center italic font-serif", children: "As novenas s\u00E3o ora\u00E7\u00F5es feitas durante nove dias consecutivos, buscando a intercess\u00E3o de Jesus, Maria ou dos santos. Esta pr\u00E1tica antiga da Igreja nos ajuda a perseverar na ora\u00E7\u00E3o e demonstrar nossa f\u00E9 e confian\u00E7a em Deus." })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: novenasData.map((novena) => (_jsx(NovenaCard, { novena: novena }, novena.id))) })] })] }));
}
